"""Add container units to Ingredient

Revision ID: 1642578a51fc
Revises: e9c2a82f2bdd
Create Date: 2025-10-03 21:16:16.219155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1642578a51fc'
down_revision = 'e9c2a82f2bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumable_unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('consumable_unit')

    # ### end Alembic commands ###
