"""Add container fields to Ingredient

Revision ID: 26af49b6a6b7
Revises: ee88f386a937
Create Date: 2025-10-03 19:31:54.599922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26af49b6a6b7'
down_revision = 'ee88f386a937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_container', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('container_prompt', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('container_prompt')
        batch_op.drop_column('is_container')

    # ### end Alembic commands ###
