"""Add subscription fields to User model

Revision ID: c5a7e5116927
Revises: 
Create Date: 2025-08-25 10:07:46.167674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a7e5116927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_credits', sa.Integer(), nullable=False, server_default='5'))
        batch_op.create_unique_constraint("uq_user_stripe_customer_id", ['stripe_customer_id'])
        batch_op.create_unique_constraint("uq_user_stripe_subscription_id", ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_stripe_subscription_id", type_='unique')
        batch_op.drop_constraint("uq_user_stripe_customer_id", type_='unique')
        batch_op.drop_column('ai_credits')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
